if __name__ == ("__main__"):
    print("1=de morse a alfabeto  , 2=de alfabeto a morse ")
    Mistring=int(input())
    if Mistring == 1:
        print("ingrese mensaje")

        morse=input()

        morse=morse.replace(".-","a")
        morse=morse.replace("-...","b")
        morse=morse.replace("-.-.","c")
        morse=morse.replace("-..","d")
        morse=morse.replace(".","e")
        morse=morse.replace("..-.","f")
        morse=morse.replace("--.","g")
        morse=morse.replace("....","h")
        morse=morse.replace("..","i")
        morse=morse.replace(".---","j")
        morse=morse.replace("-.-","k")
        morse=morse.replace(".-..","l")
        morse=morse.replace("--","m")
        morse=morse.replace("-.","n")
        morse=morse.replace("---","o")
        morse=morse.replace(".--.","p")
        morse=morse.replace("--.-","q")
        morse=morse.replace(".-.","r")
        morse=morse.replace("...","s")
        morse=morse.replace("-","t")
        morse=morse.replace("..-","u")
        morse=morse.replace("...-","v")
        morse=morse.replace(".--","w")
        morse=morse.replace("-..-","x")
        morse=morse.replace("-.--","y")
        morse=morse.replace("--..","z")

        print(morse)

    else :
        print("ingrese mensaje: ")
        alfabeto =input()
        alfabeto=alfabeto.replace("a",".-")
        alfabeto=alfabeto.replace("b","-...")
        alfabeto=alfabeto.replace("c","-.-.")
        alfabeto=alfabeto.replace("d","-..")
        alfabeto=alfabeto.replace("e",".")
        alfabeto=alfabeto.replace("f","..-.")
        alfabeto=alfabeto.replace("g","--.")
        alfabeto=alfabeto.replace("h","....")
        alfabeto=alfabeto.replace("i","..")
        alfabeto=alfabeto.replace("j",".---")
        alfabeto=alfabeto.replace("k","-.-")
        alfabeto=alfabeto.replace("l",".-..")
        alfabeto=alfabeto.replace("m","--")
        alfabeto=alfabeto.replace("n","-.")
        alfabeto=alfabeto.replace("o","---")
        alfabeto=alfabeto.replace("p",".--.")
        alfabeto=alfabeto.replace("q","--.-")
        alfabeto=alfabeto.replace("r",".-.")
        alfabeto=alfabeto.replace("s","...")
        alfabeto=alfabeto.replace("t","-")
        alfabeto=alfabeto.replace("u","..-")
        alfabeto=alfabeto.replace("v","...-")
        alfabeto=alfabeto.replace("w",".--")
        alfabeto=alfabeto.replace("x","-..-")
        alfabeto=alfabeto.replace("y","-.--")
        alfabeto=alfabeto.replace("z","--..")
        print(alfabeto)